@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Dec 18 14:27:17 +0100 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim TestBenchMIPSMulticycle_behav -key {Behavioral:sim_1:Functional:TestBenchMIPSMulticycle} -tclbatch TestBenchMIPSMulticycle.tcl -view U:/hlocal/LAB6/project_1_advanced/project_1_advanced.srcs/sim_1/imports/BASICO/Lab5_basic_homework/TestBenchMIPSMulticycle_behav1.wcfg -log simulate.log"
call xsim  TestBenchMIPSMulticycle_behav -key {Behavioral:sim_1:Functional:TestBenchMIPSMulticycle} -tclbatch TestBenchMIPSMulticycle.tcl -view U:/hlocal/LAB6/project_1_advanced/project_1_advanced.srcs/sim_1/imports/BASICO/Lab5_basic_homework/TestBenchMIPSMulticycle_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
